### ISSUE TITLE
Documentation for repeat is wrong

### ISSUE THREAD

**Issue by makoConstruct** [DefinitelyTyped/docs#3]
This page https://github.com/Reactive-Extensions/RxJS/blob/master/doc/libraries/main/rx.complete.md
links
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/repeat.md
for the instance repeat method. It appears this is the documentation static repeat method, as the instance method does not treat the first parameter as is specified hire. This may just be a simple mistake where the wrong repeat.md has been linked.

**Comment by vvakame** [comment]
Is this issue comment to this repository?

**Comment by makoConstruct** [comment]
Well the docs appear to be in the main repository, but it's an issue concerning the docs, so I reported it in the docs repository.

**Comment by vvakame** [comment]
okey, please send a pull request. thanks!

**Comment by makoConstruct** [comment]
Oh, wow.. apologies, this is not the docs repository I thought it was. I'm not sure how I made this mistake. I think I need to try to get better sleep.
